package br.com.market.storage.ui.states

import br.com.market.storage.ui.domains.ProductBrandDomain

data class FormProductUiState(
    val productName: String = "",
    val productImage: String = "",
    val brandId: Long? = null,
    val brandName: String = "",
    val brandQtd: String = "",
    val openSearch: Boolean = false,
    val brands: List<ProductBrandDomain> = mutableListOf(),
    val searchText: String = "",
    val productImageErrorMessage: String = "",
    val productNameErrorMessage: String = "",
    val brandNameErrorMessage: String = "",
    val qtdBrandErrorMessage: String = "",
    val openBrandDialog: Boolean = false,
    val onValidateBrand: () -> Boolean = { true },
    val onHideBrandDialog: () -> Unit = { },
    val onShowBrandDialog: (ProductBrandDomain?) -> Unit = { },
    val onValidateProduct: () -> Boolean = { true },
    val onProductNameChange: (String) -> Unit = { },
    val onProductImageChange: (String) -> Unit = { },
    val onBrandsChange: (ProductBrandDomain) -> Unit = { },
    val onBrandNameChange: (String) -> Unit = { },
    val onBrandQtdChange: (String) -> Unit = { },
    val onToggleSearch: () -> Unit = { },
    val onSearchChange: (String) -> Unit = { },
    override val serverMessage: String = "",
    override val showDialogMessage: Boolean = false,
    override val onToggleMessageDialog: (String) -> Unit = { },
    override val showLoading: Boolean = false,
    override val onToggleLoading: () -> Unit = { },
    override val onValidate: () -> Boolean = { false },
): BaseUiState()
